name: deploy.yml
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/TaxDocumentProcessor.Functions'
  DOTNET_VERSION: '8.0.x'
  
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal