name: deploy.yml
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/TaxDocumentProcessor.Functions'
  DOTNET_VERSION: '8.0.x'
  
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: Publish
        run: dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./publish 
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-app
          path: ./publish
          
  deploy-infrastructure:
    runs-on: ubuntu-22.04
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
              
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG}}
          template: ./infrastructure/main.bicep
          parameters: environment=dev
          scope: ''